[tools]
rojo = { github="rojo-rbx/rojo", version="7.2.1" }
selene = { github="Kampfkarren/selene", version="0.20.0" }
rbxcloud = { github = "Sleitnick/rbxcloud", version = "0.5.0" }
wally = { source = "UpliftGames/wally", version = "0.3.1" }