[package]
name = "joaquimsodre/zamngameplay"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@^1"
Shake = "sleitnick/shake@0.1.7"
Input = "sleitnick/input@2.1.1"